project:
  title: "Practical Submission"
  type: book
  render: 
    - index.qmd
  output-dir: "docs" 

book:
  title: "Parallel Practical"
  author: "Tshwanelo Nkalanga"
  sidebar:
    border: true
    background: light
    position: right
  chapters:
    - index.qmd
    - Practical Submission.qmd



